version: '3.8'

services:
  amplify:
    build: ./web
    stdin_open: true
    working_dir: '/app'
    volumes:
      - ../server:/app
      #credential,configを保管したい人向け
      - ../dev/aws/:/root/.aws/
    tty: true
