version: '3.8'

services:
  amplify:
    build: ./web
    ports:
      - 8080:8080
      - 20002:20002
    stdin_open: true
    # privileged: true
    working_dir: '/app'
    volumes:
      - ../server:/app
      #credential,configを保管したい人向け
      - ../dev/aws/:/root/.aws/
    tty: true
